/**
 * Configuration for head elements added during the creation of index.html.
 *
 * All href attributes are added the publicPath (if exists) by default.
 * You can explicitly hint to prefix a publicPath by setting a boolean value to a key that has
 * the same name as the attribute you want to operate on, but prefix with =
 *
 * Example:
 * { name: 'msapplication-TileImage', content: '/assets/icon/ms-icon-144x144.png', '=content': true },
 * Will prefix the publicPath to content.
 *
 * { rel: 'apple-touch-icon', sizes: '57x57', href: '/assets/icon/apple-icon-57x57.png', '=href': false },
 * Will not prefix the publicPath on href (href attributes are added by default
 *
 */
module.exports = {
  /**
   * tags for favicons generated by http://realfavicongenerator.net/
   */
  // link: [
  //   { rel: 'apple-touch-icon', sizes: '180x180', href: 'assets/icon/apple-touch-icon.png?v=1.10' },
  //   { rel: 'icon', type: 'image/png', sizes: '32x32', href: 'assets/icon/favicon-32x32.png?v=1.10' },
  //   { rel: 'icon', type: 'image/png', sizes: '194x194', href: 'assets/icon/favicon-194x194.png' },
  //   { rel: 'icon', type: 'image/png', sizes: '16x16', href: 'assets/icon/favicon-16x16.png' },
  //   { rel: 'icon', type: 'image/png', sizes: '192x192', href: 'assets/icon/favicon-192x192.png' },
  //   { rel: 'manifest', href: 'assets/icon/manifest.json' },
  //   { rel: 'mask-icon', href: 'assets/icon/safari-pinned-tab.svg?v=1.10', color: '#5496c6' },
  //   { rel: 'shortcut icon', href: 'assets/icon/favicon.ico?v=1.10' }
  // ],
  // meta: [
  //   { name: 'msapplication-TileColor', content: '#5496c6' },
  //   { name: 'msapplication-TileImage', content: 'assets/icon/mstile-144x144.png?v=1.10' },
  //   { name: 'msapplication-config', content: 'assets/icon/browserconfig.xml?v=1.10' },
  //   { name: 'theme-color', content: '#5496c6' }
  // ]
};
